#!/bin/sh
sed -i "s/version = .*/version = '$1'/" build.gradle
sed -i "s/.*com.github.giulioscattolin:google-gnss-logger.*/    implementation 'com.github.giulioscattolin:google-gnss-logger:$1'/" README.md